# Generated by Django 3.2.6 on 2022-03-03 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_id', models.CharField(max_length=20, verbose_name='ID в телеграме')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Chat ID в телеграме')),
                ('username', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Username в телеграме')),
                ('faith_status', models.PositiveSmallIntegerField(choices=[(0, 'Неизвестно'), (1, 'Хожу в вашу церковь'), (2, 'Хожу в другую церковь'), (3, 'Не хожу в церковь, в Бога верю'), (4, 'Не верю в Бога'), (5, 'Нет моего варианта')], default=0, verbose_name='Отношение к вере')),
                ('contact', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Дополнительный контакт')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=20, verbose_name='Ключ (англ)')),
                ('interface_name', models.CharField(max_length=30, verbose_name='Наименование пункта меню (рус)')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='порядок отображения в Телеграме')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Главное меню',
                'verbose_name_plural': 'Главное меню',
            },
        ),
        migrations.CreateModel(
            name='UppperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmbot.account', verbose_name='Суперадмин')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=20, verbose_name='Ключ (англ)')),
                ('interface_name', models.CharField(max_length=30, verbose_name='Наименование пункта меню (рус)')),
                ('order', models.PositiveSmallIntegerField(verbose_name='порядок отображения в Телеграме')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.account', verbose_name='Менеджер категории')),
                ('parent_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.mainmenu', verbose_name='Относится к пункту главного меню')),
            ],
            options={
                'verbose_name': 'Подпункт меню',
                'verbose_name_plural': 'Подпункты меню',
                'unique_together': {('order', 'parent_category')},
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='bot token')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Текст с контактами')),
                ('greeting', models.TextField(blank=True, null=True, verbose_name='Текст приветствия')),
                ('greeting_cover', models.FileField(blank=True, default=None, upload_to='static/', verbose_name='Обложка')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='tmbot.account', verbose_name='Администратор')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.city', verbose_name='Город')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastor', to='tmbot.account', verbose_name='Пастор')),
            ],
            options={
                'verbose_name': 'Настройки города',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg_id', models.CharField(max_length=20, verbose_name='ID последнего сообщения в телеграме')),
                ('last_message', models.CharField(max_length=20, verbose_name='Тело последнего сообщения в телеграме')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('request_status', models.PositiveSmallIntegerField(choices=[(0, 'Нет активных обращений'), (1, 'Обращение передано'), (2, 'Обращение отвечено (вопрос решён)'), (3, 'Обращение не отвечено (вопрос не решён)'), (4, 'Не получен ответ о завершении вопроса')], verbose_name='Код статуса ответа на обращение')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmbot.account', verbose_name='Пользователь')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tmbot.subcategories')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
