# Generated by Django 3.2.6 on 2022-03-03 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name_plural': 'Настройки города'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='bot_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='bot token'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.account', verbose_name='Менеджер категории'),
        ),
    ]
