# Generated by Django 3.2.6 on 2022-03-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0002_auto_20220303_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='interface_name',
            field=models.CharField(max_length=50, verbose_name='Наименование пункта меню (рус)'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='city',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='interface_name',
            field=models.CharField(max_length=50, verbose_name='Наименование пункта меню (рус)'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.account', verbose_name='Менеджер категории'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.mainmenu', verbose_name='Относится к пункту главного меню'),
        ),
    ]
