# Generated by Django 3.2.6 on 2022-03-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0004_auto_20220305_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
