# Generated by Django 3.2.6 on 2022-03-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0007_auto_20220305_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tmbot.account', verbose_name='Менеджер категории'),
        ),
    ]
