# Generated by Django 3.2.6 on 2022-03-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0008_mainmenu_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategories',
            old_name='type',
            new_name='kind',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='category',
        ),
        migrations.AddField(
            model_name='message',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tmbot.subcategories', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='message',
            name='request_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Нет активных обращений'), (1, 'Обращение создано'), (2, 'Обращение передано'), (3, 'Обращение отвечено (вопрос решён)'), (4, 'Обращение не отвечено (вопрос не решён)'), (5, 'Не получен ответ о завершении вопроса')], verbose_name='Код статуса ответа на обращение'),
        ),
    ]
