# Generated by Django 3.2.6 on 2022-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0010_settings_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cities',
            field=models.ManyToManyField(blank=True, null=True, to='tmbot.Settings', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='website',
            field=models.TextField(blank=True, default='church22.ru', verbose_name='Сайт'),
        ),
    ]
