# Generated by Django 3.2.6 on 2022-03-17 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0012_alter_message_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cities',
            field=models.ManyToManyField(blank=True, to='tmbot.Settings', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
