# Generated by Django 3.2.6 on 2022-03-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0013_auto_20220317_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_message',
            field=models.TextField(blank=True, null=True, verbose_name='Тело последнего сообщения в телеграме'),
        ),
    ]
