# Generated by Django 3.2.6 on 2022-03-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmbot', '0014_alter_message_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='order',
            field=models.PositiveSmallIntegerField(default=10, verbose_name='порядок отображения в Телеграме'),
        ),
    ]
